//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GestAcaLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Absence
	{
		public DateTime Date
		{
			get;
			set;
		}       
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id
		{
			get;
			set;
		}
        public virtual ICollection<Enrollment> Enrollments
        {
            get;
            set;
        }
        public static object taughCourses { get; internal set; }
    }
}

